/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ff915a",
        "primary-fixed-dim": "#f76600",
        "inverse-primary": "#a24100",
        "surface-dim": "#0c0e0f",
        "surface-variant": "#232628",
        "secondary-fixed-dim": "#cad5ed",
        "primary-fixed": "#ff7a31",
        "on-tertiary-fixed-variant": "#604100",
        "surface-container": "#171a1b",
        "error-dim": "#d53d18",
        "tertiary-fixed-dim": "#efa914",
        "outline": "#747577",
        "tertiary-container": "#ffb627",
        "tertiary-fixed": "#ffb627",
        "on-secondary": "#475266",
        "primary-dim": "#ff7526",
        "surface-container-low": "#111415",
        "on-error-container": "#ffd2c8",
        "surface-container-highest": "#232628",
        "on-secondary-fixed-variant": "#515c70",
        "surface-container-high": "#1d2021",
        "error": "#ff7351",
        "on-secondary-container": "#c5d1e8",
        "on-primary": "#531e00",
        "secondary-container": "#3c475a",
        "primary-container": "#ff7a31",
        "surface-container-lowest": "#000000",
        "on-surface": "#f6f6f7",
        "tertiary-dim": "#efa914",
        "secondary-dim": "#cad5ed",
        "background": "#0c0e0f",
        "outline-variant": "#464849",
        "on-primary-fixed": "#000000",
        "tertiary": "#ffc96f",
        "secondary": "#d8e3fb",
        "secondary-fixed": "#d8e3fb",
        "inverse-surface": "#f9f9fa",
        "on-tertiary-fixed": "#3a2600",
        "on-secondary-fixed": "#354053",
        "on-tertiary": "#614100",
        "error-container": "#b92902",
        "on-error": "#450900",
        "surface-bright": "#292d2e",
        "primary": "#ff915a",
        "on-surface-variant": "#aaabac",
        "surface": "#0c0e0f",
        "on-tertiary-container": "#553900",
        "on-background": "#f6f6f7",
        "inverse-on-surface": "#545556",
        "on-primary-fixed-variant": "#501c00",
        "on-primary-container": "#411500"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
